services:
  my_postgres_db: # Nom du mon premier service.
    image: postgres:14 # Utilise l'image officielle PostgreSQL version 14 comme base pour ce service.

    env_file:
      - .env
    # Charge les variables d'environnement définies dans le fichier .env situé dans le même dossier que docker-compose.yml.

    container_name: ${BDD_NAME}

    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data # Ajout de cette ligne pour lier le volume

  mage_ai:
    build:
      context: . # Indique service sera construit à partir d'une image Docker définie dans le répertoire courant (indiqué par le .)
      dockerfile: Dockerfile # Construit l'image de l'application à partir du fichier "Dockerfile"

    env_file:
      - .env

    container_name: ${CONT_1_NAME}

    environment:
      ENV: ${ENV}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

    ports:
      - "6789:6789"

    depends_on:
      - my_postgres_db

volumes: # À placer au même niveau que les services.
  postgres_data:
