version: 0.1.1

mon_profil_custom:
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: my_pg_db
  POSTGRES_SCHEMA: public
  POSTGRES_USER: my_user
  POSTGRES_PASSWORD: my_password
  POSTGRES_HOST: my_postgres_db
  POSTGRES_PORT: 5432

default:
  # PostgreSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: my_pg_db
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: my_user
  POSTGRES_PASSWORD: my_password
  POSTGRES_HOST: my_postgres_db
  POSTGRES_PORT: 5432
